server:
  port: 8082
  servlet:
    context-path: /yingxue
    jsp:
      init-parameters:
        development: true
spring:
  mvc:
    view:
      prefix: /
      suffix: .jsp
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/yingxue?characterEncoding=UTF-8
    username: root
    password: root
  servlet:
    multipart:
      max-file-size: 300MB  #指定服务器接收文件的大小
      max-request-size: 300MB   #允许请求的文件大小
mybatis:
  type-aliases-package: com.baizhi.entity
  mapper-locations: classpath:com/baizhi/mapper/*Mapper.xml

